#!/usr/bin/python3
import sys

hintFile = open("hint.txt", "r")
for hintLine in hintFile.readlines():
    elem = hintLine.strip().split(",")
    coreIdx = str(elem[0])

    outputFile = open("output" + coreIdx + ".txt", "r")
    outputLines = outputFile.readlines()

    for i in elem[1:]:
        print(outputLines[int(i)], end="")
