#!/usr/bin/python3
import sys

if len(sys.argv) < 2:
    print("Insufficient arguments")
    exit()

outputFile = open(sys.argv[1])
outputLines = outputFile.readlines()

hintFile = open("hint.txt", "r")
for hintLine in hintFile.readlines():
    elem = hintLine.strip().split(",")
    coreIdx = int(elem[0])
    for i in elem[1:]:
        print(outputLines[int(i)], end="")
