#!/bin/bash
source ~/.bashrc
vcss ../mat_defn.sv ../mat_inst_decoder.sv ../mat_mem.sv ../mat_data.sv ../mat_reg.sv ../mat_unit.sv ../mat_cache.sv ../mat_control.sv  ../mat_core.sv ../../switch/*.sv top_2core.sv
