#!/bin/bash
SRC='mat_defn.sv mat_inst_decoder.sv mat_mem.sv mat_data.sv mat_reg.sv mat_unit.sv mat_vec_unit.sv mat_cache.sv mat_control.sv mat_core.sv mat_core_sim.sv'
vcs -q -nc -sverilog $SRC && ./simv
