name: CMake

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  linux:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install protobuf
      run: sudo apt-get install protobuf-compiler

    - name: Configure
      run: cmake -S ${{github.workspace}}/sw -B ${{github.workspace}}/sw/build -DHAS_PROTOBUF=on

    - name: Build
      run: cmake --build ${{github.workspace}}/sw/build --parallel

  windows:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v3

    - uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: false
        install: mingw-w64-x86_64-cmake mingw-w64-x86_64-make mingw-w64-x86_64-protobuf mingw-w64-x86_64-gcc

    - name: Configure
      run: cmake -G "MinGW Makefiles" -S ./sw -B ./sw/build -DHAS_PROTOBUF=on

    - name: Build
      run: cmake --build ./sw/build --parallel

  macos:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3

    - name: Install protobuf
      run: brew install protobuf

    - name: Configure
      run: cmake -S ${{github.workspace}}/sw -B ${{github.workspace}}/sw/build -DHAS_PROTOBUF=on

    - name: Build
      run: cmake --build ${{github.workspace}}/sw/build --parallel
